config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new'

  resources :sessions, only: %i[new create]

  get 'chats/index', as: :chats
  get 'chats/show/:user_id', to: 'chats#show', as: :chat

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

# Base model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: chats
#
#  id         :integer          not null, primary key
#  a_id       :integer          not null
#  b_id       :integer          not null
#  log        :text             default([]), not null, is an Array
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_chats_on_a_id_and_b_id  (a_id,b_id) UNIQUE
#
class Chat < ApplicationRecord
  include Pair
  include Log

  class << self
    def find_for(user1, user2)
      a_id, b_id = key_pair(user1, user2)
      find_by(a_id: a_id, b_id: b_id)
    end

    def say(who_id, whom_id, text)
      a_id, b_id = key_pair(who_id, whom_id)

      msg = { who:  who_id,
              whom: whom_id,
              text: connection.quote(text),
              date: connection.quoted_date(Time.zone.now) }

      query = "select say(#{a_id}, #{b_id}, #{connection.quote msg.to_s})"
      msg if connection.execute(query) # See db/sql
    end
  end
end

app/models/concerns/log.rb
# frozen_string_literal: true

module Log
  extend ActiveSupport::Concern

  included do
  end
end

app/models/concerns/pair.rb
# frozen_string_literal: true

module Pair
  extend ActiveSupport::Concern

  included do
    alias_attribute :first_user_id,  :a_id
    alias_attribute :second_user_id, :b_id

    validates :a_id, presence: true, uniqueness: { scope: :b_id }
    validates :b_id, presence: true

    validate :a_less_then_b
  end

  class_methods do
    def key_pair(user1, user2)
      if user1.is_a?(Integer) && user2.is_a?(Integer)
        a_id = [user1, user2].min
        b_id = [user1, user2].max
      else
        a_id = [user1.id, user2.id].min
        b_id = [user1.id, user2.id].max
      end

      [a_id, b_id]
    end

    def str_key_pair(user1, user2)
      key_pair(user1, user2).join('_')
    end
  end

  protected

  def a_less_then_b
    return if Rails.env.test?
    return unless a_id && b_id
    errors[:base] << 'a should be less then b' unless a_id < b_id
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#
class User < ApplicationRecord
  validates :name,
            presence: true,
            uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Auth
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  layout 'chats'

  def index; end

  def show
    @whom = User.find_by(id: params[:user_id])
    redirect_to new_session_path unless current_user || @whom
  end
end

app/controllers/concerns/auth.rb
# frozen_string_literal: true

module Auth
  extend ActiveSupport::Concern

  included do
    before_action :auth

    helper_method :current_user
    helper_method :signed_in?
  end

  def current_user
    @current_user ||= begin
                        user_id = cookies[:user_id]
                        user_id ? User.find_by(id: user_id) : nil
                      end
  end

  def signed_in?
    current_user ? true : false
  end

  protected

  def auth
    redirect_to new_session_path unless signed_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :auth

  def new; end

  def create
    name = params[:name].downcase.strip
    if name.present? && (user = User.find_or_create_by(name: name))
      cookies[:user_id] = user.id
      redirect_to chats_path
    else
      flash.alert = 'Empty user'
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chats/_msg.html.erb
<div class="msg">

  <div class="who">
    <span class="name"><%= User.find_by(id: msg[:who])&.name || 'none' %></span>
    <sub class="date"><%= msg[:date] %></sub>
  </div>

  <div class="text">
    <%= msg[:text] %>
  </div>

</div>

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/index.html.erb
<p>Select user</p>

app/views/chats/show.html.erb
<h2><%= current_user.name %> to <%= @whom.name %></h2>

<%= form_with data: {chat_id: Chat.str_key_pair(current_user, @whom) } do |f| %>
  <%= f.text_field :text, autofocus: true, class: :text %>
<% end %>

<div class="log">
  <% Chat.find_for(current_user, @whom)&.log&.reverse&.each do |msg| %>
    <%= render 'chats/msg', msg: instance_eval(msg) %>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<title><%= APP::NAME %></title>
<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><%= render 'layouts/head' %></head>
  <body id="app" class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/chats.html.erb
<!DOCTYPE html>
<html>
  <head><%= render 'layouts/head' %></head>
  <body id="chats" class="<%= controller_name %> <%= action_name %>">

    <h1>Chats app:</h1>

    <div class="wrapper">
      <ul class="users">
        <% User.all.each do |user| %>
          <% if user != current_user %>
            <li id="<%= dom_id(user) %>"><%= link_to user.name, chat_path(user) %></li>
          <% end %>
        <% end %>
      </ul>

      <main class="chat">
        <%= yield %>
      </main>
    </div>

  </body>
</html>